// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqAuSPa7OuABYHGezU4AWsNHRCYN3oio',
    appId: '1:512001843482:web:9366e317c7b40cbea6cca3',
    messagingSenderId: '512001843482',
    projectId: 'healthq-o',
    authDomain: 'healthq-o.firebaseapp.com',
    storageBucket: 'healthq-o.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWzv7nfsaVbwQU1Y-bs7_tj23Q9MFYa8',
    appId: '1:512001843482:android:3f8643665414d9b2a6cca3',
    messagingSenderId: '512001843482',
    projectId: 'healthq-o',
    storageBucket: 'healthq-o.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdbbuAT0JvzVDpS34qdrz8wVxIfc-Z_fs',
    appId: '1:512001843482:ios:caeb98aee03d02f4a6cca3',
    messagingSenderId: '512001843482',
    projectId: 'healthq-o',
    storageBucket: 'healthq-o.firebasestorage.app',
    iosBundleId: 'com.example.healthq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdbbuAT0JvzVDpS34qdrz8wVxIfc-Z_fs',
    appId: '1:512001843482:ios:caeb98aee03d02f4a6cca3',
    messagingSenderId: '512001843482',
    projectId: 'healthq-o',
    storageBucket: 'healthq-o.firebasestorage.app',
    iosBundleId: 'com.example.healthq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqAuSPa7OuABYHGezU4AWsNHRCYN3oio',
    appId: '1:512001843482:web:e2cbe03e97871cf5a6cca3',
    messagingSenderId: '512001843482',
    projectId: 'healthq-o',
    authDomain: 'healthq-o.firebaseapp.com',
    storageBucket: 'healthq-o.firebasestorage.app',
  );
}
